name: test

on:
  push:
    branches:
      - master
      - main
  pull_request:

jobs:
  check-format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: erlef/setup-beam@v1.9.0
        with:
          otp-version: "23.2"
          gleam-version: "0.19.0"
      - run: gleam format --check src test
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.0.0
      - uses: erlef/setup-beam@v1.9.0
        with:
          otp-version: "23.2"
          gleam-version: "0.19.0"
      - uses: actions/setup-node@v2
        with:
          node-version: "lts/gallium"
      - run: gleam deps download
      - run: gleam test --target erlang
      - run: gleam test --target javascript
